In [1]:
import numpy as np

In [6]:
array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)
print(type(array))
print(array.shape)

Numpy Array: [1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
array.reshape(5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#attribute exploration of numpy array
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Array:\n", array)
print("Array Shape:", array.shape)
print("Number of Dimensions:", array.ndim)
print("Data Type:", array.dtype)
print("Size of Each Element (in bytes):", array.itemsize)
print("Total Number of Elements:", array.size)
print("Total Size of Array (in bytes):", array.nbytes)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array Shape: (2, 5)
Number of Dimensions: 2
Data Type: int64
Size of Each Element (in bytes): 8
Total Number of Elements: 10
Total Size of Array (in bytes): 80


In [29]:
#Numpay vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
sum_array = arr1 + arr2
print("Element-wise Addition:", sum_array)

# Element-wise subtraction
diff_array = arr2 - arr1
print("Element-wise Subtraction:", diff_array)

# Element-wise multiplication
prod_array = arr1 * arr2
print("Element-wise Multiplication:", prod_array)

# Element-wise division
div_array = arr2 / arr1
print("Element-wise Division:", div_array)



Element-wise Addition: [11 22 33 44 55]
Element-wise Subtraction: [ 9 18 27 36 45]
Element-wise Multiplication: [ 10  40  90 160 250]
Element-wise Division: [10. 10. 10. 10. 10.]


In [34]:
# Universal functions (ufuncs)
arr = np.array([2, 3, 4, 5, 6])

# Square root
sqrt_array = np.sqrt(arr)
print("Square Root:", sqrt_array)

# Exponential
exp_array = np.exp(arr)
print("Exponential:", exp_array)

# Natural logarithm
log_array = np.log(arr)
print("Natural Logarithm:", log_array)

# sine
sin_array = np.sin(arr)
print("Sine:", sin_array)

Square Root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Natural Logarithm: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [35]:
#array slicing and indexing
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Accessing elements by index
first_element = array[0]
third_element = array[2]
last_element = array[-1]
print("First Element:", first_element)
print("Third Element:", third_element)
print("Last Element:", last_element)

First Element: 10
Third Element: 30
Last Element: 100


In [36]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150]])
print("Original Array:\n", arr)

Original Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [39]:
print("Element at Row 1, Column 2:", arr[1, 2])  # 80
print("Second Row:", arr[1, :])                    # [ 60  70

Element at Row 1, Column 2: 80
Second Row: [ 60  70  80  90 100]


In [56]:
# arr[1:,3:]
arr[0:2,3:]

array([[ 40,  50],
       [ 90, 100]])

In [57]:
arr[0:3, 1:3]

array([[ 20,  30],
       [ 70,  80],
       [120, 130]])

In [58]:
#modifying array elements
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
arr[0, 2] = 100  # Accessing element at first row, third column
arr[1, :]  # Accessing entire second row

array([4, 5, 6])

In [66]:
arr[2,0] = 200  # Changing element at third row, first column
print("Modified Array:\n", arr)
arr[1, :] = [50, 60, 70]  # Changing entire second row
print("Modified Array:\n", arr)

Modified Array:
 [[  1   2 100]
 [ 50  60  70]
 [200   8   9]]
Modified Array:
 [[  1   2 100]
 [ 50  60  70]
 [200   8   9]]


In [71]:
#statistical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_value = np.mean(data)
median_value = np.median(data)
variance = np.var(data)
print("Variance:", variance)
print("Mean Value:", mean_value)
print("Median Value:", median_value)

std = np.std(data)
print("Standard Deviation:", std)

normalized_data = (data - mean_value) / std
print("Normalized Data:", normalized_data)

Variance: 8.25
Mean Value: 5.5
Median Value: 5.5
Standard Deviation: 2.8722813232690143
Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [72]:
#Logical opraerations
arr = np.array([10, 15, 20, 25, 30, 35, 40])
# Elements greater than 25
greater_than_25 = arr[arr > 25]
print("Elements greater than 25:", greater_than_25)
# Elements less than or equal to 20
less_equal_20 = arr[arr <= 20]
print("Elements less than or equal to 20:", less_equal_20)

Elements greater than 25: [30 35 40]
Elements less than or equal to 20: [10 15 20]


In [ ]:
arr[(arr > 15) & (arr < 35)]

array([20, 25, 30])

: 