### import numpy

In [94]:
import numpy as np
import numpy.ma as ma

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 

In [13]:
array = np.random.randint(1,20, (5,5))
array

array([[11,  7,  3, 13, 12],
       [11,  9, 11, 13,  2],
       [ 8, 11, 15, 16, 13],
       [12, 19, 15,  3,  1],
       [ 9,  3,  6,  2,  8]], dtype=int32)

Replace all the elements in the third column with 1.

In [14]:
array[ :, 2] = 1
print(array)

[[11  7  1 13 12]
 [11  9  1 13  2]
 [ 8 11  1 16 13]
 [12 19  1  3  1]
 [ 9  3  1  2  8]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 

In [15]:
a = np.arange(1, 17).reshape(4, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Replace the diagonal elements with 0.

In [16]:
np.fill_diagonal(a, 0)
a

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. olumns.


In [17]:
a = np.arange(1, 37).reshape(6, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th c

In [18]:
sub_array = a[2:5, 1:4]
sub_array

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. 

In [19]:
np_array = np.random.randint(1, 20, (5, 5))
np_array

array([[ 2, 11,  4, 12, 12],
       [12, 13, 16,  2, 12],
       [11, 14,  6, 17,  7],
       [15, 15,  7,  2, 19],
       [ 3, 17, 12,  8, 16]], dtype=int32)

In [29]:
np_array[1:-1, -1]

array([12,  7, 19], dtype=int32)

Extract the elements on the border.

In [21]:
border_elements = np.concatenate((np_array[0, :], np_array[-1, :], np_array[1:-1, 0], np_array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Border elements:
[ 2 11  4 12 12  3 17 12  8 16 12 11 15 12  7 19]


In [25]:
border_elements = np.concatenate((np_array[0, :], np_array[-1, :], np_array[:, 0], np_array[:, -1]))
border_elements

array([ 2, 11,  4, 12, 12,  3, 17, 12,  8, 16,  2, 12, 11, 15,  3, 12, 12,
        7, 19, 16], dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [35]:
#Create two NumPy arrays of shape (3, 4) filled with random integers. 
np_array_1 = np.random.randint(1, 10, (3, 4))
np_array_2 = np.random.randint(1, 10, (3, 4))
print("Array 1:")
print(np_array_1)
print("Array 2:")
print(np_array_2)


#Perform element-wise addition, subtraction, multiplication, and division.
#Addition
np_array_3 = np_array_1 + np_array_2
print("Addition:")
print(np_array_3)
#subtraction
np_array_4 = np_array_1 - np_array_2
print("Subtraction:")
print(np_array_4)
#multiplication
np_array_5 = np_array_1 * np_array_2
print("Multiplication:")
print(np_array_5)
#division
np_array_6 = np_array_1 / np_array_2
print("Division:")
print(np_array_6)

Array 1:
[[9 5 6 6]
 [8 8 5 8]
 [9 4 8 2]]
Array 2:
[[6 3 3 4]
 [7 7 2 8]
 [3 2 2 7]]
Addition:
[[15  8  9 10]
 [15 15  7 16]
 [12  6 10  9]]
Subtraction:
[[ 3  2  3  2]
 [ 1  1  3  0]
 [ 6  2  6 -5]]
Multiplication:
[[54 15 18 24]
 [56 56 10 64]
 [27  8 16 14]]
Division:
[[1.5        1.66666667 2.         1.5       ]
 [1.14285714 1.14285714 2.5        1.        ]
 [3.         2.         4.         0.28571429]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [39]:
x = np.arange(16).reshape((4, 4))
print(x)

#compute the row wise sum
print(np.sum(x, axis=1))
print(np.sum(x, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 6 22 38 54]
[24 28 32 36]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [44]:
array = np.random.randint(1, 21, size=(5, 5))
array
# compute the mean, median, standard deviation, and variance of the array
print('Mean:', np.mean(array))
print('Median:', np.median(array))
print('Standard deviation:', np.std(array))
print('Variance:', np.var(array))




Mean: 11.0
Median: 13.0
Standard deviation: 5.789645930452052
Variance: 33.52


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [48]:
array2 = np.arange(1, 10).reshape(3, 3)
print(array2)
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1)
mean = np.mean(array2)
std_dev = np.std(array2)
normalized_array = (array2 - mean) / std_dev
print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [53]:
np_array = np.random.randint(1, 10, size=(3, 3))
print(np_array)

# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting
d_array = np.random.randint(1, 10, size=(3,))
np_array += d_array
print(np_array)


[[7 4 2]
 [1 3 4]
 [3 2 1]]
[[13 12  7]
 [ 7 11  9]
 [ 9 10  6]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [57]:
Numpy_array = np.random.randint(1, 17, size=(4, 4))
print(Numpy_array)
oneD_array = np.random.randint(1, 10, size=4)
print(oneD_array)
result = Numpy_array - oneD_array
print(result)

[[15 14  8  8]
 [ 1 14 13  6]
 [10 13  9 13]
 [14  9  4  8]]
[3 1 8 2]
[[12 13  0  6]
 [-2 13  5  4]
 [ 7 12  1 11]
 [11  8 -4  6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [61]:
x = np.random.randint(1, 10, size=(3, 3))
print(x)
#compute the determinant, inverse, and eigenvalues of the matrix
print(np.linalg.det(x))
print(np.linalg.inv(x))
print(np.linalg.eig(x))

[[6 1 8]
 [3 4 3]
 [4 6 8]]
88.00000000000003
[[ 0.15909091  0.45454545 -0.32954545]
 [-0.13636364  0.18181818  0.06818182]
 [ 0.02272727 -0.36363636  0.23863636]]
EigResult(eigenvalues=array([14.98923048+0.j        ,  1.50538476+1.89860436j,
        1.50538476-1.89860436j]), eigenvectors=array([[ 0.64225218+0.j        , -0.77691301+0.j        ,
        -0.77691301-0.j        ],
       [ 0.36005639+0.j        ,  0.13763463+0.38424786j,
         0.13763463-0.38424786j],
       [ 0.67666206+0.j        ,  0.4192863 -0.23241228j,
         0.4192863 +0.23241228j]]))


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [64]:
two_trr = np.random.randint(1, 7, size=(2, 3))
print(two_trr)

three_trr = np.random.randint(1, 7, size=(3, 2))
print(three_trr)

#matrix multiplication
print(np.dot(two_trr, three_trr))

[[2 6 4]
 [5 6 3]]
[[1 1]
 [5 4]
 [5 4]]
[[52 42]
 [50 41]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [67]:
np_arry = np.arange(1, 10).reshape(3, 3)
print(np_arry)
np_array_1 = np_arry.reshape(1, 9)
print(np_array_1)
np_array_2 = np_arry.reshape(9, 1)
print(np_array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [70]:
new_np_array = np.random.randint(1, 11, size=(5, 5))
print(new_np_array)

flattened_array = new_np_array.flatten()
print(flattened_array)

#reshaped back
reshaped_array = flattened_array.reshape(5, 5)
print(reshaped_array)

[[ 2  4  9  3  3]
 [ 2 10  2  1  3]
 [ 8  1  2  9  6]
 [ 7  9  5  2  8]
 [ 7  8  6  1  3]]
[ 2  4  9  3  3  2 10  2  1  3  8  1  2  9  6  7  9  5  2  8  7  8  6  1
  3]
[[ 2  4  9  3  3]
 [ 2 10  2  1  3]
 [ 8  1  2  9  6]
 [ 7  9  5  2  8]
 [ 7  8  6  1  3]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [74]:
np_arry = np.random.randint(5, 20, size=(5, 5))
print(np_arry)

[[ 8 13 13 11  8]
 [15 15 15 13 14]
 [10 18  5  6 11]
 [12 10 12  9 14]
 [15  7 10 10  5]]


In [81]:
#use fancy indexing to extract the elements at the corners of the array
print(np_arry[0, 0])
print(np_arry[0, -1])
print(np_arry[-1, 0])
print(np_arry[-1, -1])

corners = np_arry[[0, 0, -1, -1], [0, -1,0, -1]]
print(corners)

# #use boolean indexing to set all elements greater than 10 to 10
# np_arry[np_arry > 10] = 10


8
8
15
5
[ 8  8 15  5]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [85]:
np_array44 = np.random.randint(1, 21, size=(4, 4))
np_array44

#use boolean indexing to set all elements greater than 10 to 10
result = np_array44[np_array44 > 10] = 10
print(result)

10


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [88]:
structured_array = np.array([('Alice', 25, 1.60),
                             ('Bob', 30, 1.75),
                             ('Charlie', 35, 1.65),
                             ('David', 40, 1.70),
                             ('Eve', 45, 1.67)],
                            dtype=[('name', 'U10'),
                                   ('age', 'i4'),
                                   ('weight', 'f4')])
print(structured_array)

#sort the array by age
sorted_aray = structured_array[structured_array['age'].argsort()]
print(sorted_aray)

[('Alice', 25, 1.6 ) ('Bob', 30, 1.75) ('Charlie', 35, 1.65)
 ('David', 40, 1.7 ) ('Eve', 45, 1.67)]
[('Alice', 25, 1.6 ) ('Bob', 30, 1.75) ('Charlie', 35, 1.65)
 ('David', 40, 1.7 ) ('Eve', 45, 1.67)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [93]:
#Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points
data_type = [('x', int), ('y', int)]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print(data)

distances = np.sqrt((data['x'] - data['y'])**2)
print(distances)

[(1, 2) (3, 4) (5, 6)]
[1. 1. 1.]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [101]:
#Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
array = np.random.randint(1, 21, size=(4, 4))
mask = np.ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Mask:")
print(mask)

sumunmasked = mask.sum()
print("Sum of unmasked elements:")
print(sumunmasked)


Original array:
[[ 4 18  2 18]
 [11 12 17 14]
 [20 12 19  1]
 [ 3 17 18  4]]
Mask:
[[4 -- 2 --]
 [-- -- -- --]
 [-- -- -- 1]
 [3 -- -- 4]]
Sum of unmasked elements:
14


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [102]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 7  7 13]
 [12 15  4]
 [ 8  5 20]]
Masked array:
[[-- 7 13]
 [12 -- 4]
 [8 5 --]]
Modified masked array:
[[ 8  7 13]
 [12  8  4]
 [ 8  5  8]]
