In [3]:
import numpy as np

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.arange(4)

array([0, 1, 2, 3])

In [6]:
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [7]:
a = np.array([100, 20, 31, 445, 530, 61, 72, 83, 90, 10])
np.sort(a)

array([ 10,  20,  31,  61,  72,  83,  90, 100, 445, 530])

In [10]:
a = np.arange(15)
a = a.reshape(3, 5)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 11], [20, 21], [30, 31]])

In [19]:
result = np.dot(a, b)
result

array([[140, 146],
       [320, 335]])

In [22]:
a = np.array([[1, 2, 3], [7, 8, 9]])
b = [4, 5, 6]
print(a - b)

[[-3 -3 -3]
 [ 3  3  3]]


In [23]:
a = np.random.random(10)
a

array([0.21800614, 0.36759224, 0.17899845, 0.07984526, 0.76032762,
       0.91615345, 0.76588553, 0.11958196, 0.51235509, 0.0621814 ])

In [24]:
a.max()

np.float64(0.9161534499392587)

In [25]:
a.ravel()

array([0.21800614, 0.36759224, 0.17899845, 0.07984526, 0.76032762,
       0.91615345, 0.76588553, 0.11958196, 0.51235509, 0.0621814 ])

In [26]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [31]:
a = np.random.random(10)
a

array([0.35773163, 0.24311565, 0.02361044, 0.98995573, 0.63123151,
       0.38960769, 0.00684581, 0.96010449, 0.20870209, 0.24887552])

In [33]:
a.argmax()

np.int64(3)

In [37]:
a = 10*np.random.random((3, 4))
a

array([[5.16759241, 7.89858802, 4.11844438, 0.08771538],
       [3.78725232, 7.29843474, 4.99654243, 0.38958959],
       [4.54707665, 0.92069426, 6.96994559, 0.22356505]])

In [39]:
a.shape

(3, 4)

In [41]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])