In [2]:
import numpy as np

In [3]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [6]:
a = np.array([100, 20, 31, 445, 530, 61, 72, 83, 90, 10])
np.sort(a)

array([ 10,  20,  31,  61,  72,  83,  90, 100, 445, 530])

In [7]:
a = np.arange(15)
a = a.reshape(3, 5)

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 11], [20, 21], [30, 31]])

In [11]:
result = np.dot(a, b)
result

array([[140, 146],
       [320, 335]])

In [12]:
a = np.array([[1, 2, 3], [7, 8, 9]])
b = [4, 5, 6]
print(a - b)

[[-3 -3 -3]
 [ 3  3  3]]


In [13]:
a = np.random.random(10)
a

array([0.28506871, 0.01676908, 0.30010563, 0.3266501 , 0.20786396,
       0.41627366, 0.97204708, 0.04920966, 0.19701763, 0.33210086])

In [14]:
a.max()

np.float64(0.9720470800728591)

In [15]:
a.ravel()

array([0.28506871, 0.01676908, 0.30010563, 0.3266501 , 0.20786396,
       0.41627366, 0.97204708, 0.04920966, 0.19701763, 0.33210086])

In [16]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [18]:
a = np.random.random(10)
a

array([0.00630232, 0.02191857, 0.49356634, 0.09162485, 0.21719438,
       0.20904536, 0.3343696 , 0.37181938, 0.86371759, 0.77929032])

In [19]:
a.argmax()

np.int64(8)

In [20]:
a = 10*np.random.random((3, 4))
a

array([[4.53243903, 8.21312446, 7.97823043, 2.18082022],
       [4.3533231 , 8.16506156, 0.53947166, 3.3681227 ],
       [5.2111266 , 5.70969652, 9.45438248, 1.01728598]])

In [21]:
a.shape

(3, 4)

In [22]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

**NumPy randint, full(), Flatten vs Ravel, Identity Matrix

In [25]:
a = np.random.rand(3, 4)
a

array([[0.6104036 , 0.37359008, 0.24577522, 0.61022154],
       [0.27908521, 0.41388787, 0.57068124, 0.91162159],
       [0.768274  , 0.34077655, 0.30512853, 0.93986427]])

In [28]:
a = np.random.randint(low = 0, high = 10, size=(3,4))
a

array([[8, 8, 6, 3],
       [9, 4, 3, 5],
       [4, 2, 5, 3]], dtype=int32)

In [29]:
a = np.random.randint(0, 10, (3, 4))
a

array([[5, 5, 0, 0],
       [0, 1, 0, 2],
       [6, 6, 1, 0]], dtype=int32)

In [32]:
np.full((3, 4), 8, dtype=int)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [33]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
b= np.random.randint(1, 10, (5, 5))
b

array([[1, 1, 6, 2, 7],
       [8, 1, 8, 1, 5],
       [1, 1, 7, 5, 7],
       [6, 8, 9, 2, 8],
       [5, 4, 3, 5, 7]], dtype=int32)

In [36]:
np.dot(a, b)

array([[1., 1., 6., 2., 7.],
       [8., 1., 8., 1., 5.],
       [1., 1., 7., 5., 7.],
       [6., 8., 9., 2., 8.],
       [5., 4., 3., 5., 7.]])

In [38]:
a = np.random.randint(0, 10, (2, 2))
a

array([[1, 8],
       [3, 8]], dtype=int32)

In [39]:
a.ravel()

array([1, 8, 3, 8], dtype=int32)

In [40]:
a.flatten()

array([1, 8, 3, 8], dtype=int32)

difference between ravel and flatten.

In [41]:
b = a.flatten()
c = a.ravel()

In [42]:
a[0, 0] = 99
b, c

(array([1, 8, 3, 8], dtype=int32), array([99,  8,  3,  8], dtype=int32))

In [43]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
np.append(a, [10, 20, 30, 40, 50]).reshape((4, 5), order='F')
# a

array([[ 0,  4,  8, 12, 20],
       [ 1,  5,  9, 13, 30],
       [ 2,  6, 10, 14, 40],
       [ 3,  7, 11, 10, 50]])

In [52]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
split1, split2 = np.hsplit(a, [2])
split1, split2

(array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]]))

In [58]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a[0:6] = 99
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
m = np.array([11, 12, 13])
a = np.array([x, y, z, m])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])